# Generated by Django 5.1 on 2024-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_jobpost_candidateapplications_selectcandidatejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
            ],
        ),
    ]
